name: E2E Tests
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/**"

jobs:
  build:
    if: github.event.pull_request.head.ref != 'i18n_crowdin'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          push: false
          load: false
          tags: pocket-id:test
          outputs: type=docker,dest=/tmp/docker-image.tar
          build-args: BUILD_TAGS=e2etest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/docker-image.tar
          retention-days: 1

  test-sqlite:
    if: github.event.pull_request.head.ref != 'i18n_crowdin'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./frontend
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Run Docker Container with Sqlite DB
        run: |
          docker run -d --name pocket-id-sqlite \
          -p 80:80 \
          -e APP_ENV=test \
          pocket-id:test

          docker logs -f pocket-id-sqlite &> /tmp/backend.log &

      - name: Run Playwright tests
        working-directory: ./frontend
        run: npx playwright test

      - name: Upload Frontend Test Report
        uses: actions/upload-artifact@v4
        if: always() && github.event.pull_request.head.ref != 'i18n_crowdin'
        with:
          name: playwright-report-sqlite
          path: frontend/tests/.report
          include-hidden-files: true
          retention-days: 15

      - name: Upload Backend Test Report
        uses: actions/upload-artifact@v4
        if: always() && github.event.pull_request.head.ref != 'i18n_crowdin'
        with:
          name: backend-sqlite
          path: /tmp/backend.log
          include-hidden-files: true
          retention-days: 15

  test-postgres:
    if: github.event.pull_request.head.ref != 'i18n_crowdin'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Cache PostgreSQL Docker image
        uses: actions/cache@v3
        id: postgres-cache
        with:
          path: /tmp/postgres-image.tar
          key: postgres-17-${{ runner.os }}

      - name: Pull and save PostgreSQL image
        if: steps.postgres-cache.outputs.cache-hit != 'true'
        run: |
          docker pull postgres:17
          docker save postgres:17 > /tmp/postgres-image.tar

      - name: Load PostgreSQL image from cache
        if: steps.postgres-cache.outputs.cache-hit == 'true'
        run: docker load < /tmp/postgres-image.tar

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./frontend
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Create Docker network
        run: docker network create pocket-id-network

      - name: Start Postgres DB
        run: |
          docker run -d --name pocket-id-db \
          --network pocket-id-network \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -e POSTGRES_DB=pocket-id \
          -p 5432:5432 \
          postgres:17

      - name: Wait for Postgres to start
        run: |
          for i in {1..10}; do
            if docker exec pocket-id-db pg_isready -U postgres; then
              echo "Postgres is ready"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run Docker Container with Postgres DB
        run: |
          docker run -d --name pocket-id-postgres \
          --network pocket-id-network \
          -p 80:80 \
          -e APP_ENV=test \
          -e DB_PROVIDER=postgres \
          -e DB_CONNECTION_STRING=postgresql://postgres:postgres@pocket-id-db:5432/pocket-id \
          pocket-id:test

          docker logs -f pocket-id-postgres &> /tmp/backend.log &

      - name: Run Playwright tests
        working-directory: ./frontend
        run: npx playwright test

      - name: Upload Frontend Test Report
        uses: actions/upload-artifact@v4
        if: always() && github.event.pull_request.head.ref != 'i18n_crowdin'
        with:
          name: playwright-report-postgres
          path: frontend/tests/.report
          include-hidden-files: true
          retention-days: 15

      - name: Upload Backend Test Report
        uses: actions/upload-artifact@v4
        if: always() && github.event.pull_request.head.ref != 'i18n_crowdin'
        with:
          name: backend-postgres
          path: /tmp/backend.log
          include-hidden-files: true
          retention-days: 15

  test-ldap:
    if: github.event.pull_request.head.ref != 'i18n_crowdin'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Cache LLDAP Docker image
        uses: actions/cache@v3
        id: lldap-cache
        with:
          path: /tmp/lldap-image.tar
          key: lldap-stable-${{ runner.os }}

      - name: Pull and save LLDAP image
        if: steps.lldap-cache.outputs.cache-hit != 'true'
        run: |
          docker pull nitnelave/lldap:stable
          docker save nitnelave/lldap:stable > /tmp/lldap-image.tar

      - name: Load LLDAP image from cache
        if: steps.lldap-cache.outputs.cache-hit == 'true'
        run: docker load < /tmp/lldap-image.tar

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker Image
        run: docker load -i /tmp/docker-image.tar

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci --prefer-offline --no-audit
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: Install Playwright Browsers
        working-directory: ./frontend
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Create Docker network
        run: docker network create pocket-id-network

      - name: Start LLDAP Server
        run: |
          docker run -d --name lldap \
          --network pocket-id-network \
          -p 3890:3890 \
          -p 17170:17170 \
          -e LLDAP_JWT_SECRET=secret \
          -e LLDAP_LDAP_USER_PASS=admin_password \
          -e LLDAP_LDAP_BASE_DN="dc=pocket-id,dc=org" \
          nitnelave/lldap:stable

      - name: Wait for LLDAP to start
        run: |
          for i in {1..15}; do
            if curl -s --fail http://localhost:17170/api/healthcheck > /dev/null; then
              echo "LLDAP is ready"
              break
            fi
            if [ $i -eq 15 ]; then
              echo "LLDAP failed to start in time"
              exit 1
            fi
            echo "Waiting for LLDAP... ($i/15)"
            sleep 3
          done

      - name: Install LLDAP CLI tools
        run: |
          echo 'deb http://download.opensuse.org/repositories/home:/Masgalor:/LLDAP/xUbuntu_24.04/ /' | sudo tee /etc/apt/sources.list.d/home:Masgalor:LLDAP.list
          curl -fsSL https://download.opensuse.org/repositories/home:Masgalor:LLDAP/xUbuntu_24.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_Masgalor_LLDAP.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install -y lldap-cli lldap-set-password

      - name: Setup test users in LLDAP
        run: |
          # Configure LLDAP CLI connection via environment variables
          export LLDAP_HTTPURL="http://localhost:17170"
          export LLDAP_USERNAME="admin"
          export LLDAP_PASSWORD="admin_password"

          # Create test users using the user add command
          lldap-cli user add "testuser1" "testuser1@pocket-id.org" \
            -p "password123" \
            -d "Test User 1" \
            -f "Test" \
            -l "User"
            
          lldap-cli user add "testuser2" "testuser2@pocket-id.org" \
            -p "password123" \
            -d "Test User 2" \
            -f "Test2" \
            -l "User2"

          # Create test groups - wait after each operation to ensure it completes
          lldap-cli group add "testgroup"
          sleep 2
          lldap-cli group update set "testgroup" "display_name" "Test Group"
          sleep 2

          lldap-cli group add "admingroup"
          sleep 2
          lldap-cli group update set "admingroup" "display_name" "Admin Group"
          sleep 2

          # Troubleshoot group creation
          echo "Listing groups to verify they were created:"
          lldap-cli group list

          # Try adding users to groups with retry logic
          for i in {1..3}; do
            echo "Attempt $i to add testuser1 to testgroup"
            if lldap-cli user group add "testuser1" "testgroup"; then
              echo "Successfully added testuser1 to testgroup"
              break
            else
              echo "Failed to add testuser1 to testgroup, retrying in 2 seconds..."
              sleep 2
            fi
            
            if [ $i -eq 3 ]; then
              echo "Warning: Could not add testuser1 to testgroup after 3 attempts"
            fi
          done

          for i in {1..3}; do
            echo "Attempt $i to add testuser2 to admingroup"
            if lldap-cli user group add "testuser2" "admingroup"; then
              echo "Successfully added testuser2 to admingroup"
              break
            else
              echo "Failed to add testuser2 to admingroup, retrying in 2 seconds..."
              sleep 2
            fi
            
            if [ $i -eq 3 ]; then
              echo "Warning: Could not add testuser2 to admingroup after 3 attempts"
            fi
          done

          echo "LLDAP test data setup complete"

          # Verify setup
          echo "Listing users:"
          lldap-cli user list
          echo "Listing groups:"
          lldap-cli group list

          # Verify group membership - these may fail but at least we'll see output
          echo "Listing testgroup members:"
          lldap-cli group info "testgroup" || true
          echo "Listing admingroup members:"
          lldap-cli group info "admingroup" || true

      - name: Run Docker Container with LDAP integration
        run: |
          docker run -d --name pocket-id-ldap \
          --network pocket-id-network \
          -p 80:80 \
          -e APP_ENV=test \
          -e LDAP_ENABLED=true \
          -e LDAP_URL=ldap://lldap:3890 \
          -e LDAP_BIND_DN="cn=admin,dc=pocket-id,dc=org" \
          -e LDAP_BIND_PASSWORD=admin_password \
          -e LDAP_BASE="dc=pocket-id,dc=org" \
          -e LDAP_USER_SEARCH_FILTER="(objectClass=person)" \
          -e LDAP_USER_GROUP_SEARCH_FILTER="(objectClass=groupOfNames)" \
          -e LDAP_SKIP_CERT_VERIFY=true \
          -e LDAP_ATTRIBUTE_USER_UNIQUE_IDENTIFIER="uid" \
          -e LDAP_ATTRIBUTE_USER_USERNAME="uid" \
          -e LDAP_ATTRIBUTE_USER_EMAIL="mail" \
          -e LDAP_ATTRIBUTE_USER_FIRST_NAME="givenName" \
          -e LDAP_ATTRIBUTE_USER_LAST_NAME="sn" \
          -e LDAP_ATTRIBUTE_GROUP_UNIQUE_IDENTIFIER="cn" \
          -e LDAP_ATTRIBUTE_GROUP_NAME="cn" \
          -e LDAP_ATTRIBUTE_GROUP_MEMBER="member" \
          -e LDAP_ATTRIBUTE_ADMIN_GROUP="admingroup" \
          -e LDAP_SOFT_DELETE_USERS=true \
          pocket-id/pocket-id:test

          docker logs -f pocket-id-ldap &> /tmp/backend.log &

      - name: Wait for backend to sync LDAP data
        run: sleep 10

      - name: Run Playwright tests
        working-directory: ./frontend
        run: npx playwright test tests/ldap

      - name: Upload Frontend Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-ldap
          path: frontend/tests/.report
          include-hidden-files: true
          retention-days: 15

      - name: Upload Backend Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-ldap
          path: /tmp/backend.log
          include-hidden-files: true
          retention-days: 15
